// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKu2J_vsWthCCDP1GsvbV3KMSXpmbT2Zs',
    appId: '1:289293180848:web:13d07fc793aa491ded0075',
    messagingSenderId: '289293180848',
    projectId: 'scie-7f98b',
    authDomain: 'scie-7f98b.firebaseapp.com',
    storageBucket: 'scie-7f98b.appspot.com',
    measurementId: 'G-381DTLCC2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Lh7flRFE8lhGsD0vhzOnpxVzFVk_2ns',
    appId: '1:289293180848:android:f1052185a4cfc1b3ed0075',
    messagingSenderId: '289293180848',
    projectId: 'scie-7f98b',
    storageBucket: 'scie-7f98b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxT2bd6SREwCnAYHxMPgC4B7NzRQEc8E',
    appId: '1:289293180848:ios:6ad61e6c053bf476ed0075',
    messagingSenderId: '289293180848',
    projectId: 'scie-7f98b',
    storageBucket: 'scie-7f98b.appspot.com',
    iosClientId: '289293180848-6kmioa1r81h9k5jmbjo2ltr37260budk.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.scientia',
  );
}
